- id: whattheprecommit
  name: Commit Roulette
  description: Ensures no one in your repo ever writes a professional commit message again.
  entry: wtc
  language: rust
  stages: [prepare-commit-msg]
